_extends: .github

repository:
  is_template: true

branches:
  - name: my-solution
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts:
          - quality-checks
          - cicd
      restrictions:
      required_signatures: false
      enforce_admins:
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

teams:
  - name: bots
    permission: push
