# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

name: CI/CD
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  pull_request:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash -Eeuo pipefail -x {0}
jobs:
  cicd:
    # if: ${{ github.event_name == 'push' }}  # ignore pull_request event
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ !startsWith(github.event.head_commit.message ,'chore(release):') }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          # token: ${{ secrets.GH_PAT_SEM_REL }}
          persist-credentials: false
          fetch-depth: 0
          set-safe-directory: true

      # - name: Log in to the GHCR
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test
        run: |
          # docker pull ghcr.io/dy-interviews/devcontainer
          docker-compose build
          docker-compose run --rm test

      - name: Release
        uses: DynamicYield/action-semrel@master
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
        with:
          ghcr-token: ${{ secrets.GH_DY_PAT_RO }}
          github-token: ${{ secrets.GH_PAT_SEM_REL }}
